/**
 *  @file oglplus/site-config.hpp
 *  @brief System configuration options
 *
 *  @author Matus Chochlik
 *
 *  Copyright 2010-2013 Matus Chochlik. Distributed under the Boost
 *  Software License, Version 1.0. (See accompanying file
 *  LICENSE_1_0.txt or copy at http://www.boost.org/LICENSE_1_0.txt)
 */
#ifndef OGLPLUS_SITE_CONFIG_120305_HPP
#define OGLPLUS_SITE_CONFIG_120305_HPP

#if 0
#define OGLPLUS_LOW_PROFILE 0
#endif

#define OGLPLUS_USE_GLCOREARB_H 1
#define OGLPLUS_USE_GL3_H 0
#define OGLPLUS_USE_GLEW 0
#define OGLPLUS_USE_GL3W 0

#define OGLPLUS_FREEGLUT_FOUND 1
#define OGLPLUS_OPENAL_FOUND false

#define OGLPLUS_USE_BOOST_CONFIG 0

#if !OGLPLUS_USE_BOOST_CONFIG
#ifndef OGLPLUS_NO_SCOPED_ENUMS
#define OGLPLUS_NO_SCOPED_ENUMS 0
#endif

#ifndef OGLPLUS_NO_VARIADIC_MACROS
#define OGLPLUS_NO_VARIADIC_MACROS 0
#endif

#ifndef OGLPLUS_NO_VARIADIC_TEMPLATES
#define OGLPLUS_NO_VARIADIC_TEMPLATES 0
#endif

#ifndef OGLPLUS_NO_UNIFIED_INITIALIZATION_SYNTAX
#define OGLPLUS_NO_UNIFIED_INITIALIZATION_SYNTAX 0
#endif

#ifndef OGLPLUS_NO_INITIALIZER_LISTS
#define OGLPLUS_NO_INITIALIZER_LISTS 0
#endif

#ifndef OGLPLUS_NO_DEFAULTED_FUNCTIONS
#define OGLPLUS_NO_DEFAULTED_FUNCTIONS 0
#endif

#ifndef OGLPLUS_NO_DELETED_FUNCTIONS
#define OGLPLUS_NO_DELETED_FUNCTIONS 0
#endif

#ifndef OGLPLUS_NO_EXPLICIT_CONVERSION_OPERATORS
#define OGLPLUS_NO_EXPLICIT_CONVERSION_OPERATORS 0
#endif

#ifndef OGLPLUS_NO_FUNCTION_TEMPLATE_DEFAULT_ARGS
#define OGLPLUS_NO_FUNCTION_TEMPLATE_DEFAULT_ARGS 0
#endif

#ifndef OGLPLUS_NO_USER_DEFINED_LITERALS
#define OGLPLUS_NO_USER_DEFINED_LITERALS 0
#endif

#ifndef OGLPLUS_NO_CONSTEXPR
#define OGLPLUS_NO_CONSTEXPR 0
#endif

#ifndef OGLPLUS_NO_NOEXCEPT
#define OGLPLUS_NO_NOEXCEPT 0
#endif

#ifndef OGLPLUS_NO_LAMBDAS
#define OGLPLUS_NO_LAMBDAS 0
#endif

#ifndef OGLPLUS_NO_NULLPTR
#define OGLPLUS_NO_NULLPTR 0
#endif


#endif // !OGLPLUS_USE_BOOST_CONFIG


#ifndef OGLPLUS_NO_CHRONO
#define OGLPLUS_NO_CHRONO 0
#endif

#ifndef OGLPLUS_NO_THREADS
#define OGLPLUS_NO_THREADS 0
#endif

#endif
