#ifndef LOD_OGLWRAP_CONFIG_H_
#define LOD_OGLWRAP_CONFIG_H_

#define OGLWRAP_DEBUG 1
#define OGLWRAP_USE_IMAGEMAGICK 1
#define OGLWRAP_PORTABILITY_MODE 1
#define OGLWRAP_INITIALIZE_GLOBAL_GL_OBJECTS_ON_USE 0
#define OGLWRAP_DEFAULT_SHADER_PATH "shaders/"

#include "oglwrap/glew.h"

#endif // LOD_OGLWRAP_CONFIG_H_
